name: platformer
description: A lightweight and minimal platform-detection utility package.
version: 1.0.0
homepage: https://github.com/IbrahimKhatrii/platformer
repository: https://github.com/IbrahimKhatrii/platformer
issue_tracker: https://github.com/IbrahimKhatrii/platformer/issues
license: MIT

environment:
  sdk: ^3.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
