name: platforms
description: A lightweight and minimal platform-detection utility package.
version: 1.0.0
homepage: https://github.com/IbrahimKhatrii/platforms
repository: https://github.com/IbrahimKhatrii/platforms
issue_tracker: https://github.com/IbrahimKhatrii/platforms/issues
license: MIT

environment:
  sdk: ^3.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
